# reusable workflow for publishing a rock
name: Build and publish rock

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        default: '.'
        type: string
      source-branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        default: ''
        required: false
        type: string
  workflow_dispatch:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        default: '.'
        type: string
      source-branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        default: ''
        required: false
        type: string

jobs:
  build-publish-rock:
    name: Build and publish rock
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/build_and_publish_rock.yaml@main
    with:
      rock-dir: ${{ inputs.rock-dir }}
      source-branch: ${{ inputs.source-branch }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
